name: CI

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: content checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: instal dependencies
        run: yarn install --frozen-lockfile
      - name: run tests
        run: yarn test:ci
        env:
          CI: true
