name: CI

on:
  pull_request:
    branches: ['develop']
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: content checkout
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: instal dependencies
        run: yarn install --frozen-lockfile
      - name: run tests
        run: yarn test:ci
        env:
          CI: true
      - name: build project
        if: github.event_name == 'push'
        run: yarn export
      - name: list project data
        run: ls -a -l
      - name: Publish project in surge
        if: github.event_name == 'push'
        run: npx surge --project ./out --domain alien-regrets.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
