name: container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14.16.0-alpine3.13
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
