name: Set out example

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Do your work
        run: |
          echo "FAV_NUMBER=3" >> $GITHUB_OUTPUT
          echo "FAV_COLOR=blue" >> $GITHUB_OUTPUT
        id: abc
      - name: Read output
        run: |
          echo "${{ steps.abc.outputs.FAV_NUMBER }}"
          echo "${{ steps.abc.outputs.FAV_COLOR }}"
      - name: Set output
        id: stepid
        run: echo "name=count=5" >> $GITHUB_OUTPUT
      - name: Use prior output
        run: echo "The count was ${{ steps.stepid.outputs.count }}"
    outputs:
      fav-animal: tiger
      fav-number: ${{steps.abc.outputs.FAV_NUMBER}}
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{needs.job1.outputs.fav-animal}}"
          echo "${{needs.job1.outputs.fav-number}}"
